version: '3.4'
networks:
  dev:
    driver: bridge
services:
  product-api:
    image: docker.io/library/productapi
    depends_on:
      - "product_db"
    container_name: productapi-service
    ports:
      - "5009:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID =postgres;Password=postgres;Server=product_db;Port=5432;Database=ProductDb; Integrated Security=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  product_db:
    image: postgres:latest
    container_name: product_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ProductDb
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - product_data:/var/lib/postgresql/data
    networks:
      - dev
volumes:
  product_data: